# Generated by Django 3.0.5 on 2021-06-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationwindow',
            name='questions',
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='application_window',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='applications.ApplicationWindow', verbose_name='application_window'),
            preserve_default=False,
        ),
    ]
