# Generated by Django 3.0.5 on 2021-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20210622_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationquestion',
            name='statement',
            field=models.CharField(max_length=225),
        ),
    ]
