# Generated by Django 3.0.5 on 2021-06-23 12:45

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20210622_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='username',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='application_window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='applications.ApplicationWindow', verbose_name='application_window'),
        ),
    ]
