# Generated by Django 3.0.5 on 2021-06-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20210623_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
