# Generated by Django 3.0.5 on 2021-06-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20210623_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='username',
        ),
    ]
