# Generated by Django 3.0.5 on 2021-06-23 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_applicant_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicant',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='username',
        ),
        migrations.AddField(
            model_name='applicant',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
