# Generated by Django 3.0.5 on 2021-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20210623_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
