# Generated by Django 3.0.5 on 2021-06-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20210623_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='reg_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
