# Generated by Django 3.0.5 on 2021-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20210629_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
