# Generated by Django 3.0.5 on 2021-02-19 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=5000)),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('college', models.CharField(blank=True, max_length=255)),
                ('programme', models.CharField(blank=True, max_length=255)),
                ('study_period', models.IntegerField(blank=True, choices=[(3, 'Three'), (4, 'Four')], default=3)),
                ('year_of_study', models.IntegerField(blank=True, default=2021)),
                ('admission_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A title', max_length=255, unique=True)),
                ('bussiness_idea', models.TextField(blank=True)),
                ('problem_solved', models.TextField(blank=True)),
                ('value_it_brings', models.TextField(blank=True)),
                ('to_whom', models.TextField(blank=True)),
                ('is_profitable', models.BooleanField(blank=True, default=False)),
                ('members_in_udsm', models.BooleanField(blank=True, default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
