# Generated by Django 3.0.5 on 2021-02-24 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_all', models.BooleanField(blank=True, default=False)),
                ('email_subject', models.CharField(default='Udicti', max_length=255)),
                ('email_body', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('to', models.ManyToManyField(blank=True, related_name='mails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
