# Generated by Django 3.0.5 on 2021-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='project_pics'),
        ),
    ]
