# Generated by Django 3.1.6 on 2021-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210212_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='bussiness_idea',
        ),
        migrations.AddField(
            model_name='project',
            name='group_size',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='in_group',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='members_in_udsm',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='problem_solved',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='to_whom',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='project',
            name='value_it_brings',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admission_date',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='programme',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='study_period',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
