# Generated by Django 3.1.6 on 2021-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210212_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profitable',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
