# Generated by Django 3.0.5 on 2021-04-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210414_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_cover',
            field=models.ImageField(null=True, upload_to='project_pics/cover'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(null=True, upload_to='project_pics/avatar'),
        ),
    ]
