# Generated by Django 3.1.6 on 2021-02-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_profitable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='study_period',
            field=models.CharField(choices=[(3, 'Three'), (4, 'Four')], default=3, max_length=1),
        ),
    ]
