# Generated by Django 3.0.5 on 2021-04-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_topproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
    ]
