# Generated by Django 3.0.5 on 2021-04-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_userprofile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='study_period',
            field=models.IntegerField(blank=True, choices=[(3, 'Three'), (4, 'Four')], default=3, null=True),
        ),
    ]
