# Generated by Django 3.0.5 on 2021-04-18 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20210418_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_profitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='members_in_udsm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_cover',
            field=models.ImageField(blank=True, upload_to='project_pics/cover'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, upload_to='project_pics/avatar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='A Project title', max_length=255, unique=True),
        ),
    ]
