# Generated by Django 3.0.5 on 2021-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210418_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproject',
            name='accomplishments',
            field=models.TextField(blank=True),
        ),
    ]
