# Generated by Django 3.0.5 on 2021-04-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_topproject_accomplishments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topproject',
            old_name='Project',
            new_name='project',
        ),
    ]
