# Generated by Django 3.0.5 on 2021-04-19 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('to_post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='api.BlogPost')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_likes', to=settings.AUTH_USER_MODEL)),
                ('to_project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_likes', to='api.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
