# Generated by Django 3.0.5 on 2021-04-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210419_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='to_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Project'),
        ),
    ]
