# Generated by Django 3.0.5 on 2021-06-22 12:19

import ckeditor.fields
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210502_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('university', models.CharField(max_length=255)),
                ('degree_program', models.CharField(max_length=255)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_unselected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('applicants', models.ManyToManyField(related_name='application', to='api.Applicant', verbose_name='applicant')),
                ('questions', models.ManyToManyField(related_name='application_window', to='api.ApplicationQuestion', verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', ckeditor.fields.RichTextField()),
                ('from_applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Applicant')),
                ('to_question', models.ManyToManyField(related_name='answers', to='api.ApplicationQuestion')),
            ],
        ),
    ]
