# Generated by Django 3.0.5 on 2021-06-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_answer_applicant_applicationquestion_applicationwindow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='to_question',
        ),
        migrations.AddField(
            model_name='answer',
            name='to_question',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.ApplicationQuestion'),
            preserve_default=False,
        ),
    ]
