# Generated by Django 3.0.5 on 2021-06-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210622_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='username',
        ),
    ]
