# Generated by Django 3.0.5 on 2021-06-22 12:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_applicant_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationquestion',
            name='statement',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='applicationwindow',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='application', to='api.Applicant', verbose_name='applicant'),
        ),
    ]
