# Generated by Django 3.0.5 on 2021-06-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210622_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationwindow',
            name='applicants',
        ),
        migrations.AddField(
            model_name='applicant',
            name='application_window',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.ApplicationWindow'),
            preserve_default=False,
        ),
    ]
