# Generated by Django 3.0.5 on 2021-06-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210622_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='from_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Applicant'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.ApplicationQuestion'),
        ),
    ]
