# Generated by Django 3.0.5 on 2021-06-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210622_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='application_window',
        ),
        migrations.RemoveField(
            model_name='applicationwindow',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='ApplicationQuestion',
        ),
        migrations.DeleteModel(
            name='ApplicationWindow',
        ),
    ]
