# Generated by Django 3.0.5 on 2021-12-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_attendance_attendancecode_attendancelist_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
