# Generated by Django 3.0.5 on 2021-12-07 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_attendance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time created'),
        ),
    ]
