# Generated by Django 3.0.5 on 2021-12-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_attendance_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='attendancelist',
            old_name='day',
            new_name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
