# Generated by Django 3.0.5 on 2021-12-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20211211_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='api.Event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='attendancecode',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance_codes', to='api.Event', verbose_name='event'),
        ),
    ]
