# Generated by Django 3.0.5 on 2021-12-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20211211_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='on_going',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
