# Generated by Django 3.0.5 on 2022-01-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_teams_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True, default=2022),
        ),
    ]
