# Generated by Django 3.0.5 on 2022-02-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20220204_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'third Year'), (4, 'Fourth Year'), (5, 'Fifth Year')], default=1),
        ),
    ]
